---
- name: Wait for APIs to become available
  command: >
    {{ openshift_client_binary }} get --raw /apis/{{ item }}/v1
  register: openshift_apis
  until: openshift_apis.rc == 0
  with_items: "{{ l_core_api_list }}"
  retries: 60
  delay: 5

- name: Get API logs
  command: >
    /usr/local/bin/master-logs api api
  register: control_plane_logs_api
  ignore_errors: true
  when: openshift_apis is failed

- debug:
    msg: "{{ control_plane_logs_api.stdout_lines }}"
  when: openshift_apis is failed

- fail:
    msg: >
      API did not become available. Verbose curl output and API logs
      have been collected above to assist with debugging.
  when: openshift_apis is failed
