apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearchs.elasticsearch.redhat.com
spec:
  group: elasticsearch.redhat.com
  names:
    kind: Elasticsearch
    listKind: ElasticsearchList
    plural: elasticsearchs
    singular: elasticsearch
  scope: Namespaced
  version: v1alpha1
